id: Eradication plan - Test
version: -1
name: Eradication plan - Test
description: |
  This playbook tests the ‘Eradication Plan’ playbook which is part of the ‘Common Playbooks’ pack.
  he playbook includes the following conducted tests to check if the eradication actions were performed properly.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: b6e92da3-1700-46d9-86b9-5afb44ee9f00
    type: start
    task:
      id: b6e92da3-1700-46d9-86b9-5afb44ee9f00
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -610
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 83977c56-6701-4b37-8842-49b85b72eed1
    type: title
    task:
      id: 83977c56-6701-4b37-8842-49b85b72eed1
      version: -1
      name: Test without inputs
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "17"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -465
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 54357bf5-0911-47ed-88e5-c75eb76aa6ca
    type: title
    task:
      id: 54357bf5-0911-47ed-88e5-c75eb76aa6ca
      version: -1
      name: Test with inputs
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "18"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 10
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 1ccb44da-d4e4-4242-8de4-089517d7724b
    type: regular
    task:
      id: 1ccb44da-d4e4-4242-8de4-089517d7724b
      version: -1
      name: Set Path
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      append:
        simple: "true"
      key:
        simple: Path
      value:
        simple: C:\Windows\System32\notepad.exe
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 850
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 9fa8f623-1b36-4610-893a-a6463414a5dc
    type: condition
    task:
      id: 9fa8f623-1b36-4610-893a-a6463414a5dc
      version: -1
      name: Verify eradication action succeed
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "11"
      "yes":
      - "10"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: TerminatedProcessFromEndpoints
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1210
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: 104cf899-ac2a-4bf5-815b-732e28101bba
    type: title
    task:
      id: 104cf899-ac2a-4bf5-815b-732e28101bba
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 5507444c-048d-4259-8aa1-85661696a565
    type: regular
    task:
      id: 5507444c-048d-4259-8aa1-85661696a565
      version: -1
      name: Make test fail
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      message:
        simple: The eradication plan playbook has failed. Please check the output of the eradication sub-playbooks.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 740,
          "y": 1400
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: b641faad-0649-4ebd-8100-aacdbf7088bc
    type: regular
    task:
      id: b641faad-0649-4ebd-8100-aacdbf7088bc
      version: -1
      name: Set Endpoint ID
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      key:
        simple: Endpoints
      value:
        simple: '["0cc51a9cd88147e4b70cd83e93ab5814","47bdca96e01b45b38bd9d3a80f2b9dbe","e02ad5e911094a358a271be1c9833284","6aec3d18d2404b3e84da227948583c4e","8b4aecf600f14313b23f7f31ed64b58c","561e3c2320884d979353513cf2fd14f2","98210476acd34d8b877e55b83196da29","ac848acbd7504115b6624c9b1d755000"]'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 490
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: ccbfc672-f455-4b1f-84a9-ef435f996473
    type: regular
    task:
      id: ccbfc672-f455-4b1f-84a9-ef435f996473
      version: -1
      name: Get Endpoints
      description: Gets a list of endpoints, according to the passed filters. If there are no filters, all endpoints are returned. Filtering by multiple fields will be concatenated using AND condition (OR is not supported). Maximum result set size is 100. Offset is the zero-based number of endpoint from the start of the result set (start by counting from 0).
      script: '|||core-get-endpoints'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 320
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: e2cced3e-9e9a-4a00-82c5-65836495af67
    type: regular
    task:
      id: e2cced3e-9e9a-4a00-82c5-65836495af67
      version: -1
      name: Compare Endpoints ID
      description: Compare  two lists and put the differences in context.
      scriptName: CompareLists
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "19"
      - "7"
    scriptarguments:
      left:
        complex:
          root: Core.Endpoint
          accessor: endpoint_id
      right:
        complex:
          root: Endpoints
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 670
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 93c4740c-74b3-42e2-8e37-3d8630728eeb
    type: playbook
    task:
      id: 93c4740c-74b3-42e2-8e37-3d8630728eeb
      version: -1
      name: Eradication Plan
      playbookName: Eradication Plan
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 8ec5d52c-fe98-4a9c-88bf-2278d03e0e1d
    type: playbook
    task:
      id: 8ec5d52c-fe98-4a9c-88bf-2278d03e0e1d
      version: -1
      name: Eradication Plan
      playbookName: Eradication Plan
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      AutoEradicate:
        simple: "True"
      EndpointID:
        complex:
          root: ListCompare
          accessor: Both
      FilePath:
        complex:
          root: Path
      FileRemediation:
        simple: Delete
      ProcessTermination:
        simple: Name
      UserRemediation:
        simple: "True"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1020
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "17":
    id: "17"
    taskid: 9eb18de0-45b2-4baa-842a-1cca96cced50
    type: regular
    task:
      id: 9eb18de0-45b2-4baa-842a-1cca96cced50
      version: -1
      name: Delete all context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "15"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -335
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: f5325ab9-2821-45ac-85eb-47cf05efb2b1
    type: regular
    task:
      id: f5325ab9-2821-45ac-85eb-47cf05efb2b1
      version: -1
      name: Delete all context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 145
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "19":
    id: "19"
    taskid: 1b0c28c8-4c99-4b12-8d8b-5fd34c5b2959
    type: regular
    task:
      id: 1b0c28c8-4c99-4b12-8d8b-5fd34c5b2959
      version: -1
      name: run process
      description: Initiate a new endpoint script execution of shell commands.
      script: '|||core-run-script-execute-commands'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      commands:
        simple: notepad.exe
      endpoint_ids:
        complex:
          root: ListCompare
          accessor: Both
      timeout:
        simple: "500"
    separatecontext: false
    continueonerror: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 40,
          "y": 850
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {
      "9_10_yes": 0.53
    },
    "paper": {
      "dimensions": {
        "height": 2255,
        "width": 1080,
        "x": 40,
        "y": -610
      }
    }
  }
inputs: []
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.6.0