id: Enrichment for Verdict - Test
version: -1
name: Enrichment for Verdict - Test
description: |-
  This playbook tests the ‘Enrichment for Verdict’ playbook which is part of the ‘Common Playbooks’ pack.
  The playbook includes the following conducted tests:
  - Checks the enrichment of the url.
  - Checks the enrichment of the file.
  - Checks the enrichment of the domain.
  - Checks the enrichment of the account.
  - Checks if the DBotScore exist.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ba4e42fc-4be2-43ce-85c1-90e9c66d97db
    type: start
    task:
      id: ba4e42fc-4be2-43ce-85c1-90e9c66d97db
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -750
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "3":
    id: "3"
    taskid: 7d40ed21-8525-4a73-80b4-880abb2f66c3
    type: regular
    task:
      id: 7d40ed21-8525-4a73-80b4-880abb2f66c3
      version: -1
      name: Set domain
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      key:
        simple: DomainName
      value:
        simple: demisto.com
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 350
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 05d0abaa-08e9-41dc-8dee-04940f0ab8f4
    type: regular
    task:
      id: 05d0abaa-08e9-41dc-8dee-04940f0ab8f4
      version: -1
      name: Clear context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 0
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "6":
    id: "6"
    taskid: 148575ba-f04b-4746-8bb3-563799c76070
    type: regular
    task:
      id: 148575ba-f04b-4746-8bb3-563799c76070
      version: -1
      name: Set hash
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      key:
        simple: FileSHA256
      value:
        simple: afd3b729cf99fb9ea441f42862a4835d1d6eeb36ee535f9b206e3a00382c972e
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 530
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 019be3c9-991c-4e93-84f0-849113d6e63c
    type: regular
    task:
      id: 019be3c9-991c-4e93-84f0-849113d6e63c
      version: -1
      name: Set IP
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      key:
        simple: IP
      value:
        simple: 1.1.1.1
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 710
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "8":
    id: "8"
    taskid: 7f55f69d-f947-4d59-8c05-ef4920bff04f
    type: condition
    task:
      id: 7f55f69d-f947-4d59-8c05-ef4920bff04f
      version: -1
      name: Did the enrichment process succeed?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "9"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: DBotScore
                accessor: Score
            iscontext: true
          right:
            value: {}
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: FileVerdict
            iscontext: true
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: Account
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1050
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "9":
    id: "9"
    taskid: 2d64ac2d-902e-4666-8133-3cfec4303b8d
    type: title
    task:
      id: 2d64ac2d-902e-4666-8133-3cfec4303b8d
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1430
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "10":
    id: "10"
    taskid: e76cb8c5-2506-478e-8ad0-d349d2e78672
    type: regular
    task:
      id: e76cb8c5-2506-478e-8ad0-d349d2e78672
      version: -1
      name: |
        Make the test fail
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      message:
        simple: Enrichment for verdict has failed. Please check the conditions and see which one was not met, or if another error has occurred during the enrichment process.
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 720,
          "y": 1250
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "11":
    id: "11"
    taskid: 598e8a5e-2f93-475d-8b50-e10e33cd73e7
    type: regular
    task:
      id: 598e8a5e-2f93-475d-8b50-e10e33cd73e7
      version: -1
      name: Set User
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      key:
        simple: User
      value:
        simple: DEM449982
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "12":
    id: "12"
    taskid: 23e0fcb7-49ef-469f-83c7-dcc8586ebeea
    type: playbook
    task:
      id: 23e0fcb7-49ef-469f-83c7-dcc8586ebeea
      version: -1
      name: Enrichment for Verdict
      playbookName: Enrichment for Verdict
      type: playbook
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "15"
    separatecontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -300
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "13":
    id: "13"
    taskid: 8f6435ed-7614-41aa-81ef-cb7fe24c3279
    type: title
    task:
      id: 8f6435ed-7614-41aa-81ef-cb7fe24c3279
      version: -1
      name: Test Without any Inputs
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "14"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -610
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "14":
    id: "14"
    taskid: 27efd6db-bf90-4e3e-8955-bef848572570
    type: regular
    task:
      id: 27efd6db-bf90-4e3e-8955-bef848572570
      version: -1
      name: Clear context
      description: |-
        Delete field from context.

        This automation runs using the default Limited User role, unless you explicitly change the permissions.
        For more information, see the section about permissions here:
        https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.10/Cortex-XSOAR-Administrator-Guide/Automations
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      all:
        simple: "yes"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -470
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "15":
    id: "15"
    taskid: 05feb5df-5cb3-4472-85ab-f50cf7d4fd9d
    type: title
    task:
      id: 05feb5df-5cb3-4472-85ab-f50cf7d4fd9d
      version: -1
      name: Test With Inputs
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": -140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 4875039d-68d1-4950-82b8-48da0a5ad821
    type: playbook
    task:
      id: 4875039d-68d1-4950-82b8-48da0a5ad821
      version: -1
      name: Enrichment for Verdict
      description: This playbook checks prior alert closing reasons and performs enrichment and prevalence checks on different IOC types. It then  returns the information needed to establish the alert's verdict.
      playbookName: Enrichment for Verdict
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      CloseReason:
        simple: Resolved - False Positive,Resolved - Duplicate Incident,Resolved - Known Issue
      Domain:
        complex:
          root: inputs.Domain
      FileSHA256:
        complex:
          root: inputs.FileHash
      IP:
        complex:
          root: inputs.IP
      URL:
        complex:
          root: inputs.Url
      UseReputationCommand:
        simple: "True"
      User:
        complex:
          root: inputs.User
      query:
        simple: (initiatorsha256:${inputs.FileSHA256} or hostip:${inputs.IP}) and sourceBrand:"${alert.sourceBrand}" and name:"${alert.name}"
      threshold:
        simple: "2"
    separatecontext: true
    continueonerrortype: ""
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 450,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2245,
        "width": 650,
        "x": 450,
        "y": -750
      }
    }
  }
inputs:
- key: IP
  value:
    complex:
      root: IP
  required: false
  description: ""
  playbookInputQuery:
- key: Url
  value:
    complex:
      root: URL
  required: false
  description: ""
  playbookInputQuery:
- key: Domain
  value:
    complex:
      root: DomainName
  required: false
  description: ""
  playbookInputQuery:
- key: FileHash
  value:
    complex:
      root: FileSHA256
  required: false
  description: sha256
  playbookInputQuery:
- key: User
  value:
    complex:
      root: User
  required: false
  description: ""
  playbookInputQuery:
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.6.0
marketplaces:
- marketplacev2